[Service]
Environment="HHD_DISTRO=yaguarete"
Environment="HHD_PPD_MASK=1"
Environment="HHD_ALLY_POWERSAVE=1"
Environment="HHD_HORI_STEAM=1"
Environment="HHD_GS_STEAMUI_HALFHZ=1"
Environment="HHD_GS_DPMS=1"
Environment="HHD_GS_STANDBY=1"
Environment="HHD_GS_FRAMEGEN=1"
Environment="HHD_GS_AUTOLOGIN=1"
Environment="HHD_GS_CEC=1"
Environment="HHD_HIDE_ALL=1"
Environment="HHD_BOOTC=1"
Environment="HHD_BUGREPORT=1"
Environment="HHD_BOOTC_FALLBACK_IMG=i.anatase.org/anatase:stable"
Environment="HHD_ADJUSTOR_NEXT=1"
Environment="HHD_BOOTC_SOFT_REBOOT=1"
Environment="HHD_SWAP_CREATE=1"