[Network]
default_on_boot = FIRST_WIRED_WITH_LINK

[Bootloader]
# This block is not used for atomic systems, bootupd is used instead
efi_dir = yaguarete
menu_auto_hide = True

[User Interface]
hidden_spokes =
    NetworkSpoke
    PasswordSpoke
    UserSpoke
hidden_webui_pages =
    anaconda-screen-accounts
    anaconda-screen-date-time
webui_web_engine = slitherer

[Storage]
default_scheme = BTRFS
btrfs_compression = zstd:1
default_partitioning =
    /     (min 1 GiB, max 70 GiB)
    /var  (btrfs)
    /var/home (min 500 MiB, free 50 GiB)
